#!/usr/bin/env python3
"""Generates pipewire-hal.conf from the FuriOS file pipewire-droid.conf.

Instead of a copy, only one thing is inserted:
  1. api.droid.* -> our SPA plugin in context.spa-libs
  (device and nodes are created by WirePlumber, see wireplumber/droid.lua)

That way later FuriOS changes to pipewire-droid.conf are carried along as soon
as this script is run again.
"""
import re
import sys

NODE = ""   # device and nodes come from WirePlumber (droid.lua)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src).read()

    # 1) register the SPA library
    if "api.droid." in text:
        print("note: api.droid.* is already in the template", file=sys.stderr)
    else:
        m = re.search(r"^context\.spa-libs\s*=\s*\{\s*$", text, re.M)
        if not m:
            print("ERROR: context.spa-libs not found", file=sys.stderr)
            return 1
        insert = m.end() + 1
        text = (text[:insert]
                + "    api.droid.*     = droid/libspa-droid\n"
                + text[insert:])

    # 2) append the device
    m = re.search(r"^context\.objects\s*=\s*\[\s*$", text, re.M)
    if not m:
        print("ERROR: context.objects not found", file=sys.stderr)
        return 1
    insert = m.end() + 1
    text = text[:insert] + NODE + text[insert:]

    header = ("# Generated by gen-pipewire-hal-conf.py from %s\n"
              "# Do NOT edit by hand - run the script again instead.\n" % src)
    open(dst, "w").write(header + text)
    print("%s -> %s" % (src, dst))
    return 0


if __name__ == "__main__":
    sys.exit(main())
