#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 misc-de
# SPDX-License-Identifier: MIT
"""The parts written in Python, and the seam between the app and audioctl.

That seam is the interesting one. The app reads audioctl's output line by line
and looks for labels; renaming a label in audioctl - which happened while
translating the project to English - silently breaks the app, and nothing
notices until someone opens it and sees "unknown".
"""
import importlib.util
import re
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class ConfigGenerator(unittest.TestCase):
    """gen-pipewire-hal-conf.py rewrites FuriOS' own config."""

    def setUp(self):
        self.gen = ROOT / "gen-pipewire-hal-conf.py"
        self.template = (
            "# Daemon config file\n"
            "context.properties = {\n"
            "    default.clock.rate = 48000\n"
            "}\n"
            "context.spa-libs = {\n"
            "    audio.convert.* = audioconvert/libspa-audioconvert\n"
            "}\n"
            "context.objects = [\n"
            "]\n"
        )

    def run_gen(self, text, tmp):
        src, dst = tmp / "in.conf", tmp / "out.conf"
        src.write_text(text)
        res = subprocess.run([sys.executable, str(self.gen), str(src), str(dst)],
                             capture_output=True, text=True)
        return res, dst

    def test_registers_the_plugin(self):
        import tempfile
        with tempfile.TemporaryDirectory() as d:
            res, dst = self.run_gen(self.template, Path(d))
            self.assertEqual(res.returncode, 0, res.stderr)
            out = dst.read_text()
            self.assertIn("api.droid.*", out)
            self.assertIn("droid/libspa-droid", out)

    def test_keeps_what_furios_had(self):
        """The point of generating instead of copying: their changes survive."""
        import tempfile
        with tempfile.TemporaryDirectory() as d:
            _, dst = self.run_gen(self.template, Path(d))
            out = dst.read_text()
            self.assertIn("audio.convert.*", out)
            self.assertIn("default.clock.rate = 48000", out)

    def test_says_so_when_the_template_changed(self):
        """A silent pass on a template it did not understand would be worse."""
        import tempfile
        with tempfile.TemporaryDirectory() as d:
            res, _ = self.run_gen("nothing we recognise\n", Path(d))
            self.assertNotEqual(res.returncode, 0)
            self.assertIn("context.spa-libs", res.stderr)

    def test_marks_the_file_as_generated(self):
        import tempfile
        with tempfile.TemporaryDirectory() as d:
            _, dst = self.run_gen(self.template, Path(d))
            head = dst.read_text().splitlines()[0]
            self.assertIn("Generated by", head)


class AppReadsAudioctl(unittest.TestCase):
    """The switcher app parses audioctl's status output."""

    @classmethod
    def setUpClass(cls):
        sys.modules.setdefault("gi", None)
        cls.audioctl = (ROOT / "audioctl").read_text()
        cls.app = (ROOT / "gui" / "furios-audio-switch.py").read_text()

    def labels_in_app(self):
        return re.findall(r'line\.startswith\("([^"]+)"\)', self.app)

    def test_every_label_the_app_looks_for_is_one_audioctl_prints(self):
        for label in self.labels_in_app():
            with self.subTest(label=label):
                self.assertIn(label, self.audioctl,
                              "the app waits for a line audioctl never prints")

    def test_the_app_looks_for_something_at_all(self):
        """Guards the test above from passing by finding nothing."""
        self.assertGreaterEqual(len(self.labels_in_app()), 4)

    def test_test_mode_is_recognised_by_the_word_audioctl_uses(self):
        self.assertIn('startswith("yes")', self.app)
        self.assertRegex(self.audioctl, r"Test mode:\s+yes")

    def test_the_dmnr_switch_speaks_the_words_the_script_understands(self):
        script = (ROOT / "experiments" / "dmnr-handsfree.sh").read_text()
        self.assertIn('"on" if row.get_active() else "off"', self.app)
        # The script dispatches on these exact words; the app sends them.
        for word in ("on)", "off)"):
            self.assertRegex(script, r"(?m)^%s$" % re.escape(word))

    def test_the_machine_readable_state_line_matches(self):
        script = (ROOT / "experiments" / "dmnr-handsfree.sh").read_text()
        self.assertIn("state=on", script)
        self.assertIn('"state=on" in out', self.app)


class PauseOnDisconnect(unittest.TestCase):
    """The watcher that keeps music off the loudspeaker."""

    def test_it_only_reacts_to_a_lost_connection(self):
        src = (ROOT / "tools" / "furios-audio-pause-on-disconnect.py").read_text()
        self.assertIn('changed.get("Connected") is False', src)
        self.assertIn("org.bluez.Device1", src)

    def test_it_pauses_rather_than_muting_anything(self):
        src = (ROOT / "tools" / "furios-audio-pause-on-disconnect.py").read_text()
        self.assertIn('"Pause"', src)
        self.assertNotIn("set-sink-mute", src)
        self.assertNotIn("set_mute", src)

    def test_it_leaves_players_that_are_not_playing_alone(self):
        src = (ROOT / "tools" / "furios-audio-pause-on-disconnect.py").read_text()
        self.assertIn('status == "Playing"', src)


if __name__ == "__main__":
    unittest.main(verbosity=2)
